image: Visual Studio 2017
version: 1.0.{build}
init:
  - git config --global core.autocrlf input
build_script:
- ps: >-
    dotnet restore OkLogger.sln --source https://api.nuget.org/v3/index.json

        dotnet build OKLogger.sln

        if($env:APPVEYOR_REPO_TAG -eq "true")
        {
          dotnet pack src\OKLogger\OKLogger.csproj --configuration Release --output ..\..\output /p:Version=$env:APPVEYOR_REPO_TAG_NAME
        }
        else
        {
          dotnet pack src\OKLogger\OKLogger.csproj --configuration Release --output ..\..\output /p:Version=0.0.1-build-$env:APPVEYOR_BUILD_NUMBER
        }
test_script:
- ps: dotnet test .\src\OKLogger.Tests\OKLogger.Tests.csproj
- ps: dotnet test src\OKLogger.PerformanceTests\OKLogger.PerformanceTests.csproj
artifacts:
- path: output\**.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: //tKHlb2yqAtpxnR6p9IAtXwQNaq8UYYyIFSD0QVF3XnEasIxG2gTWdmWuG87fUX
  on:
    appveyor_repo_tag: true